spring.application.name=fortuna-bank-servers
server.port=8083

#Redis
spring.data.redis.host=192.168.1.102
spring.data.redis.port=6379
spring.session.store-type=redis

#Postgres
spring.datasource.url=jdbc:postgresql://192.168.1.102:5432/user_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional JPA settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#Keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://192.168.1.102:8080/realms/fortuna-bank-mobile-app-realm/protocol/openid-connect/certs




