spring.application.name=fortuna-bank-servers
server.port=8081



spring.security.oauth2.client.registration.keycloak.client-id=fortuna-bank-mobile-client
spring.security.oauth2.client.registration.keycloak.client-secret=MIB0mmLOG34szkVAkrY7diYM3C49MDTh
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8080/login/oauth2/code/fortuna-bank-mobile-client

spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/fortuna-bank-mobile-app-realm







